version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: jumba-postgres
    environment:
      POSTGRES_DB: jumba
      POSTGRES_USER: jumba
      POSTGRES_PASSWORD: abmuj101!!
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
